"""Public vocabulary snapshot, independent of store.enums.

KO-580 adds the loop's missing phase edges to the pre-KO-579 baseline."""

BASELINE = {'PHASES': ('claimed',
            'working',
            'verifying',
            'reviewing',
            'addressing',
            'merge_gate',
            'awaiting_merge_approval',
            'merging',
            'squashing',
            'done',
            'blocked_on_operator',
            'failed',
            'killed',
            'rejected'),
 'TICKET_TRANSITIONS': {'needs_spec': frozenset({'ready'}),
                        'ready': frozenset({'blocked_on_deps', 'in_flight'}),
                        'in_flight': frozenset({'abandoned',
                                                'blocked_on_operator',
                                                'merged'}),
                        'blocked_on_deps': frozenset({'ready', 'blocked_on_operator'}),
                        'blocked_on_operator': frozenset({'blocked_on_deps'}),
                        'merged': frozenset(),
                        'abandoned': frozenset()},
 'INTERVENTION_ACTIONS': ('redirect',
                          'kill',
                          'extend_time_box',
                          'resume',
                          'close_out',
                          'requeue',
                          'approve',
                          'repoint',
                          'babysit',
                          'reconcile',
                          'restart_supervisor',
                          'launch_loop',
                          'launch_backoff',
                          'route_fallback',
                          'config_edit',
                          'operator_note',
                          'migrate',
                          'hold',
                          'release_hold'),
 'PARKED_PHASES': frozenset({'awaiting_merge_approval', 'blocked_on_operator'}),
 'RUN_PHASE_TRANSITIONS': {'claimed': frozenset({'awaiting_merge_approval',
                                                 'failed',
                                                 'killed',
                                                 'merge_gate',
                                                 'working'}),
                           'working': frozenset({'failed', 'verifying', 'killed'}),
                           'verifying': frozenset({'awaiting_merge_approval',
                                                   'failed', 'reviewing', 'killed'}),
                           'reviewing': frozenset({'addressing', 'verifying',
                                                   'awaiting_merge_approval',
                                                   'failed',
                                                   'killed',
                                                   'merge_gate'}),
                           'addressing': frozenset({'failed', 'verifying', 'killed'}),
                           'merge_gate': frozenset({'awaiting_merge_approval',
                                                    'verifying',
                                                    'failed',
                                                    'killed',
                                                    'merging',
                                                    'rejected'}),
                           'awaiting_merge_approval': frozenset({'done',
                                                                 'failed',
                                                                 'killed',
                                                                 'rejected'}),
                           'merging': frozenset({'done', 'failed', 'killed',
                                                 'verifying', 'merge_gate',
                                                 'awaiting_merge_approval',
                                                 'blocked_on_operator'}),
                           'squashing': frozenset(),
                           'done': frozenset(),
                           'failed': frozenset({'addressing',
                                                'reviewing',
                                                'verifying',
                                                'working'}),
                           'blocked_on_operator': frozenset({'working'}),
                           'killed': frozenset(),
                           'rejected': frozenset()}}
