"""A red Playwright witness is an assertion red only when every failed test is."""
import unittest

from holophyte.story.witness import red_kind
from tests.test_witness_go_red_kind import UNITTEST_ASSERTION_RED

ASSERTION_BESIDE_PASS = (
    "Running 2 tests using 1 worker\n"
    "\n"
    "(node:36292) Warning: The 'NO_COLOR' env is ignored due to the 'FORCE_CO"
    "LOR' env being set.\n"
    "(Use `node --trace-warnings ...` to show where the warning was created)\n"
    "  ✘  1 assert.spec.ts:2:5 › version switch keeps documents (2ms)\n"
    "(node:36292) Warning: The 'NO_COLOR' env is ignored due to the 'FORCE_CO"
    "LOR' env being set.\n"
    "(Use `node --trace-warnings ...` to show where the warning was created)\n"
    "  ✓  2 assert.spec.ts:5:5 › passes (2ms)\n"
    "\n"
    "\n"
    "  1) assert.spec.ts:2:5 › version switch keeps documents ───────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(received).toBe(expected) // Object.is equality\n"
    "\n"
    "    Expected: 4\n"
    "    Received: 3\n"
    "\n"
    "      1 | import { test, expect } from '@playwright/test';\n"
    "      2 | test('version switch keeps documents', async () => {\n"
    "    > 3 |   expect([1, 2, 3].length).toBe(4);\n"
    "        |                            ^\n"
    "      4 | });\n"
    "        at /tmp/w/assert.spec.ts:3:28\n"
    "\n"
    "    Error Context: test-results/assert-version-switch-keeps-documents/er"
    "ror-context.md\n"
    "\n"
    "  1 failed\n"
    "    assert.spec.ts:2:5 › version switch keeps documents ────────────────"
    "────────────────────────────\n"
    "  1 passed (381ms)\n")
POLL_AND_SOFT = (
    "Running 2 tests using 1 worker\n"
    "\n"
    "  ✘  1 poll.spec.ts:2:5 › poll (361ms)\n"
    "  ✘  2 poll.spec.ts:3:5 › soft (2ms)\n"
    "\n"
    "\n"
    "  1) poll.spec.ts:2:5 › poll ───────────────────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(received).toBe(expected) // Object.is equality\n"
    "\n"
    "    Expected: 2\n"
    "    Received: 1\n"
    "\n"
    "    Call Log:\n"
    "    - Timeout 500ms exceeded while waiting on the predicate\n"
    "\n"
    "        at /tmp/w/poll.spec.ts:2:79\n"
    "\n"
    "    Error Context: test-results/poll-poll/error-context.md\n"
    "\n"
    "  2) poll.spec.ts:3:5 › soft ───────────────────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(received).toBe(expected) // Object.is equality\n"
    "\n"
    "    Expected: 2\n"
    "    Received: 1\n"
    "\n"
    "        at /tmp/w/poll.spec.ts:3:43\n"
    "\n"
    "    Error Context: test-results/poll-soft/error-context.md\n"
    "\n"
    "  2 failed\n"
    "    poll.spec.ts:2:5 › poll ────────────────────────────────────────────"
    "────────────────────────────\n"
    "    poll.spec.ts:3:5 › soft ────────────────────────────────────────────"
    "────────────────────────────\n")
LOCATOR_ASSERTION = (
    "Running 1 test using 1 worker\n"
    "\n"
    "  ✘  1 locator.spec.ts:2:5 › selector shows (658ms)\n"
    "\n"
    "\n"
    "  1) locator.spec.ts:2:5 › selector shows ──────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(locator).toBeVisible() failed\n"
    "\n"
    "    Locator: locator('#contractVersionSelector')\n"
    "    Expected: visible\n"
    "    Timeout: 500ms\n"
    "    Error: element(s) not found\n"
    "\n"
    "    Call log:\n"
    "      - Expect \"toBeVisible\" locator('#contractVersionSelector') with ti"
    "meout 500ms\n"
    "      - waiting for locator('#contractVersionSelector')\n"
    "\n"
    "\n"
    "    > 4 |   await expect(page.locator('#contractVersionSelector')).toBeV"
    "isible({ timeout: 500 });\n"
    "        |                                                          ^\n"
    "        at /tmp/w/locator.spec.ts:4:58\n"
    "\n"
    "    Error Context: test-results/locator-selector-shows/error-context.md\n"
    "\n"
    "  1 failed\n"
    "    locator.spec.ts:2:5 › selector shows ───────────────────────────────"
    "────────────────────────────\n")
THROWN_ERROR = (
    "Running 1 test using 1 worker\n"
    "\n"
    "  ✘  1 throws.spec.ts:2:5 › draft loads (0ms)\n"
    "\n"
    "\n"
    "  1) throws.spec.ts:2:5 › draft loads ──────────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: fixture draft missing\n"
    "\n"
    "    > 3 |   throw new Error('fixture draft missing');\n"
    "        |         ^\n"
    "        at /tmp/w/throws.spec.ts:3:9\n"
    "\n"
    "    Error Context: test-results/throws-draft-loads/error-context.md\n"
    "\n"
    "  1 failed\n"
    "    throws.spec.ts:2:5 › draft loads ───────────────────────────────────"
    "────────────────────────────\n")
TEST_TIMEOUT = (
    "Running 1 test using 1 worker\n"
    "\n"
    "  ✘  1 timeout.spec.ts:2:5 › slow (2.0s)\n"
    "\n"
    "\n"
    "  1) timeout.spec.ts:2:5 › slow ────────────────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Test timeout of 2000ms exceeded.\n"
    "\n"
    "    Error Context: test-results/timeout-slow/error-context.md\n"
    "\n"
    "  1 failed\n"
    "    timeout.spec.ts:2:5 › slow ─────────────────────────────────────────"
    "────────────────────────────\n")
ACTION_TIMEOUT = (
    "Running 1 test using 1 worker\n"
    "\n"
    "  ✘  1 locator.spec.ts:6:5 › click missing (556ms)\n"
    "\n"
    "\n"
    "  1) locator.spec.ts:6:5 › click missing ───────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    TimeoutError: locator.click: Timeout 500ms exceeded.\n"
    "    Call log:\n"
    "      - waiting for locator('#nope')\n"
    "\n"
    "\n"
    "    >  8 |   await page.locator('#nope').click({ timeout: 500 });\n"
    "         |                               ^\n"
    "        at /tmp/w/locator.spec.ts:8:31\n"
    "\n"
    "    Error Context: test-results/locator-click-missing/error-context.md\n"
    "\n"
    "  1 failed\n"
    "    locator.spec.ts:6:5 › click missing ────────────────────────────────"
    "────────────────────────────\n")
LOCATOR_BESIDE_ACTION_TIMEOUT = (
    "Running 2 tests using 1 worker\n"
    "\n"
    "  ✘  1 locator.spec.ts:2:5 › selector shows (658ms)\n"
    "  ✘  2 locator.spec.ts:6:5 › click missing (556ms)\n"
    "\n"
    "\n"
    "  1) locator.spec.ts:2:5 › selector shows ──────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(locator).toBeVisible() failed\n"
    "\n"
    "    Locator: locator('#contractVersionSelector')\n"
    "    Expected: visible\n"
    "    Timeout: 500ms\n"
    "    Error: element(s) not found\n"
    "\n"
    "    Call log:\n"
    "      - Expect \"toBeVisible\" locator('#contractVersionSelector') with ti"
    "meout 500ms\n"
    "      - waiting for locator('#contractVersionSelector')\n"
    "\n"
    "\n"
    "    > 4 |   await expect(page.locator('#contractVersionSelector')).toBeV"
    "isible({ timeout: 500 });\n"
    "        |                                                          ^\n"
    "        at /tmp/w/locator.spec.ts:4:58\n"
    "\n"
    "    Error Context: test-results/locator-selector-shows/error-context.md\n"
    "\n"
    "  2) locator.spec.ts:6:5 › click missing ───────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    TimeoutError: locator.click: Timeout 500ms exceeded.\n"
    "    Call log:\n"
    "      - waiting for locator('#nope')\n"
    "\n"
    "\n"
    "    >  8 |   await page.locator('#nope').click({ timeout: 500 });\n"
    "         |                               ^\n"
    "        at /tmp/w/locator.spec.ts:8:31\n"
    "\n"
    "    Error Context: test-results/locator-click-missing/error-context.md\n"
    "\n"
    "  2 failed\n"
    "    locator.spec.ts:2:5 › selector shows ───────────────────────────────"
    "────────────────────────────\n"
    "    locator.spec.ts:6:5 › click missing ────────────────────────────────"
    "────────────────────────────\n")
ASSERTION_BESIDE_THROWN_ERROR = (
    "Running 2 tests using 1 worker\n"
    "\n"
    "  ✘  1 assert.spec.ts:2:5 › version switch keeps documents (2ms)\n"
    "  ✘  2 throws.spec.ts:2:5 › draft loads (0ms)\n"
    "\n"
    "\n"
    "  1) assert.spec.ts:2:5 › version switch keeps documents ───────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: expect(received).toBe(expected) // Object.is equality\n"
    "\n"
    "    Expected: 4\n"
    "    Received: 3\n"
    "\n"
    "      1 | import { test, expect } from '@playwright/test';\n"
    "      2 | test('version switch keeps documents', async () => {\n"
    "    > 3 |   expect([1, 2, 3].length).toBe(4);\n"
    "        |                            ^\n"
    "      4 | });\n"
    "        at /tmp/w/assert.spec.ts:3:28\n"
    "\n"
    "    Error Context: test-results/assert-version-switch-keeps-documents/er"
    "ror-context.md\n"
    "\n"
    "  2) throws.spec.ts:2:5 › draft loads ──────────────────────────────────"
    "────────────────────────────\n"
    "\n"
    "    Error: fixture draft missing\n"
    "\n"
    "    > 3 |   throw new Error('fixture draft missing');\n"
    "        |         ^\n"
    "        at /tmp/w/throws.spec.ts:3:9\n"
    "\n"
    "    Error Context: test-results/throws-draft-loads/error-context.md\n"
    "\n"
    "  2 failed\n"
    "    assert.spec.ts:2:5 › version switch keeps documents ────────────────"
    "────────────────────────────\n"
    "    throws.spec.ts:2:5 › draft loads ───────────────────────────────────"
    "────────────────────────────\n")
NEVER_READY = (
    "!! never became ready\n"
    "[server] listening on :3000 failed: EADDRINUSE\n"
    "[server] exiting with code 1\n")


class CapturedPlaywrightOutputTests(unittest.TestCase):
    def test_a_failed_expect_beside_a_passing_test_is_an_assertion_red(self):
        self.assertEqual(red_kind(ASSERTION_BESIDE_PASS), "assert")

    def test_failed_poll_and_soft_expects_are_an_assertion_red(self):
        self.assertEqual(red_kind(POLL_AND_SOFT), "assert")

    def test_a_locator_expect_with_its_nested_error_line_is_an_assertion_red(self):
        self.assertEqual(red_kind(LOCATOR_ASSERTION), "assert")

    def test_a_thrown_error_and_both_timeouts_are_exception_reds(self):
        for name, output in (("thrown", THROWN_ERROR), ("test timeout", TEST_TIMEOUT),
                             ("action timeout", ACTION_TIMEOUT)):
            with self.subTest(name):
                self.assertEqual(red_kind(output), "exception")

    def test_an_expect_beside_a_thrown_error_is_an_exception_red(self):
        for name, output in (("thrown", ASSERTION_BESIDE_THROWN_ERROR),
                             ("action timeout", LOCATOR_BESIDE_ACTION_TIMEOUT)):
            with self.subTest(name):
                self.assertEqual(red_kind(output), "exception")

    def test_a_boot_failure_with_no_playwright_summary_is_an_exception_red(self):
        self.assertEqual(red_kind(NEVER_READY), "exception")

    def test_a_playwright_red_beside_a_unittest_red_follows_every_summary(self):
        self.assertEqual(red_kind(UNITTEST_ASSERTION_RED + POLL_AND_SOFT), "assert")
        self.assertEqual(red_kind(UNITTEST_ASSERTION_RED + THROWN_ERROR), "exception")
        self.assertEqual(red_kind(POLL_AND_SOFT + THROWN_ERROR), "exception")


if __name__ == "__main__":
    unittest.main()
